config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :posts,     shallow: true do
      resources :comments,  shallow: true
    end
  end
  get "/control_panel", to: "users#control_panel"
  devise_for :users
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body
  # validates :user_id, presence: true

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable

  def find_parent_post
    return self.commentable if self.commentable.is_a?(Post)
    self.commentable.find_parent_post # semi recursion will keep calling itself until it .is_a? Post
  end
end

app/models/forum.rb
class Forum < ApplicationRecord
  validates :name, length: { minimum: 3 }
  validates :description, length: { minimum: 20 }
  validates :user_id, presence: true

  belongs_to :user
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :forum_id, presence: true

  belongs_to :user
  belongs_to :forum

  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :forums
  has_many :posts

  def comment_post_hash
    @comment_hash = []
    @user_comments = Comment.where(user_id: self.id)
    @user_comments.all.each do |co|
       post = co.find_parent_post
      @comment_hash.push( { comment: co, post: post} )
    end
    @comment_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @forums = Forum.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(params[:post_id]) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to control_panel_path, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.update_attributes(body: 'This comment has been deleted', user_id: nil, is_deleted: true)
    respond_to do |format|
      #format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def all_comments
      @comments = Comment.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id, :parent_id, :commentable_id, :commentable_type, :user_id)
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = current_user.forums.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description, :references, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # For comment form on post page.
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Forum.find(params[:forum_id]).posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        @forum = Forum.find(@post.forum_id)
        # format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.html { redirect_to forum_posts_path(@forum, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :forum_id).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:control_panel]

  def control_panel
    @comments = @user.comment_post_hash
  end

  private

  def find_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<h1>Hot Forums</h1>

<ul>
  <% @forums.each do |f| %>
  <li><%= link_to f.name, forum_path(f) %></li>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(comment) do |f| %>
      <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control"%>
      </div>
      <br>
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").remove();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= comment.parent_id %></td>
        <td><%# link_to 'Show', comment %></td>
        <td><%# link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%# link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%#= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%#= @comment.post %>
</p>

<p>
  <strong>Parent:</strong>
  <%#= @comment.parent_id %>
</p>

<%# link_to 'Edit', edit_comment_path(@comment) %> <!-- edit_forums_post_comments_path or something -->

app/views/forums/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Name and Description</h2>
    <%= form_for(forum, :html => {class: "form-group"}) do |f| %>
      <% if forum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

          <ul>
          <% forum.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control"%>
      </div>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
        <%= f.hidden_field :user_id %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All forums</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table">
      <tbody>
        <% @forums.each do |forum| %>
          <tr class="forum-rows" data-link="<%= forum_path(forum) %>">
            <td><%= forum.name %></td>
            <td><%= forum.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1>New Forum</h1>
<%= render 'form', forum: @forum %>

app/views/forums/show.html.erb
<% if @forum.user == current_user %>
  <%= link_to 'Forum Control Panel', edit_forum_path(@forum) %>
<% end %>
<br>

<%= link_to "Add Post", new_forum_post_path(@forum), class: "btn btn-primary" %> <%= link_to 'Back', root_path, class: "btn btn-primary" %>

<div class="well">
  <p>
    <strong>Name:</strong>
    <%= @forum.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @forum.description %>
  </p>
</div>

<% if @forum.posts.any? %>
  <p>
    <strong>Posts:</strong>
    <% @forum.posts.each do |p| %>
      <ul>
        <li><%= link_to p.title, post_path(p) %></li>
      </ul>
    <% end %>
  </p>
<% else %>
  <p>There are no posts yet.</p>
<% end %>

<%= link_to "Hot forums", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uni-Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/nav" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% unless current_page?('/') %>
        <%= link_to "Hot Forums", root_path %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :url => {:controller => "posts", :action => "create"} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    <%= f.hidden_field :forum_id %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Users</th>
      <th>Forums</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%# link_to 'Show', post %></td>
        <td><%# link_to 'Edit', edit_post_path(post) %></td>
        <td><%# link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h2>Post:</h2>
<div class="well">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>
<% if @post.description %>
  <p>
    <strong>Description:</strong>
    <%= @post.description %>
  </p>
<% end %>
</div>

<% if current_user %>
  <%= render partial: "shared/comment_form", :locals => { commentable_type: @post.class.name, commentable_id: @post.id } if current_user %>
<% else %>
  <p>Log in to add comments</p>
<% end %>

<% if @post.comments.any? %>
  <%= render "shared/comment_list" %>
<% else %>
  <p>No comments yet</p>
<% end %>

app/views/shared/_comment_form.html.erb
<div class="form-group comment-form">
  <%= form_for @comment, remote: true, url: post_comments_path(@post) do |f| %>
    <%= f.text_area :body, required: true, rows: 5, class: "form-control" %>
    <%= f.hidden_field :commentable_id, :value => commentable_id %>
    <%= f.hidden_field :commentable_type, :value => commentable_type %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <br>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>
<span class="add-comment">Add a comment</span>

app/views/shared/_comment_list.html.erb
<div class="comment-list">
  <h2>Comments</h2>
  <ul>
    <% @post.comments.each do |c| %>
      <li><%= c.body %></li>
      <% unless c.is_deleted == true %>
        <%= render partial: "shared/comment_form", :locals => { commentable_type: c.class.name, commentable_id: c.id, post: @post.id } if current_user %>
      <% end %>
      <ul>
        <% c.comments.each do |d| %>
          <li><%= d.body %></li>
          <% unless d.is_deleted == true %>
            <%= render partial: "shared/comment_form", :locals => { commentable_type: d.class.name, commentable_id: d.id, post: @post.id } if current_user %>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </ul>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Uni-Forum</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All forums", forums_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Control panel", control_panel_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <li><%= link_to "Create forum", new_forum_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/comment_form.js.erb
$('.comment-form').hide().after('<%#= j render("comment_form") %>');

app/views/users/control_panel.html.erb
<h2>Control Panel:</h2>


<div class="col-md-10 col-md-offset-1">
  <% if @comments.any? %>
  <h3>Recent comments:</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Comment</th>
        <th>Post</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @comments.each do |co| %>
        <tr id="<%= dom_id(co[:comment]) %>">
          <td><%= truncate(co[:comment].body, length: 50) %></td>
          <td><%= truncate(co[:post].title, length: 50) %></td>
          <td>
              <%= link_to 'destroy', comment_path(co[:comment]), remote: true, method: :delete, data: {confirm: 'Are you sure you want to delete this comment?'} %> |
              <%= link_to 'edit', edit_comment_path(co[:comment])  %> |
              <%= link_to 'go to post', post_path(co[:post]) %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
  <% else %>
    <h4>You haven't made any comments yet!</h4>
  <% end %>
</div>

app/views/users/control_panel.js.erb
$("#comment-<%= @co[:comment].id %>").remove();

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>